name: alt_bangumi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  equatable: ^2.0.5
  extended_image: ^7.0.2
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_riverpod: ^2.3.4
  flutter_secure_storage: ^8.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html_core: ^0.14.6
  fluttertoast: ^8.2.4
  go_router: ^12.0.1
  html: ^0.15.4
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  photo_view: ^0.14.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shimmer: ^3.0.0
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  sliver_tools: ^0.2.12
  url_launcher: ^6.1.11
  webview_flutter: ^4.4.2

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  patrol: ^3.4.0
  patrol_finders: ^2.0.1+1
  slang_build_runner: ^3.25.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bgm/
    - assets/images/musume/
    - assets/images/static/
    - assets/json/
    - assets/json/substrings/
    - secrets.json
  # app_name: Alt Bangumi
  # localizations:
  #   - locale: en
  #     title: Alt Bangumi
  #   - locale: zh-cn
  #     title: 班固米
  #   - locale: zh-tw
  #     title: 班固米
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/images/logo_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_1024.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_1024.png"

flutter_native_splash:
  background_image: assets/images/splash.png
  background_image_dark: assets/images/splash_dark.png

patrol:
  app_name: Alt Bangumi
  android:
    package_name: com.kerojohn.alt_bangumi
  ios:
    bundle_id: com.kerojohn.alt_bangumi
  macos:
    bundle_id: com.kerojohn.alt_bangumi
