name: Android Release

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:
    name: GET alt bangumi app version from pubspec.yaml
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: GET version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' ./pubspec.yaml)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
  
  android_build:
    name: CREATE Android Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      
      - name: DOWNLOAD Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@784a1a4a994315802b7d8e2084e116e783d157be # v1.2.4
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: CREATE key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: "11.0.18"
          distribution: temurin
             
      - name: Clone Flutter repository
        uses: subosito/flutter-action@cc97e1648fff6ca5cc647fa67f47e70f7895510b # v2.11.0
        with:
          flutter-version: '3.16.4'
          cache: true
      
      - name: GET dependencies
        run: flutter pub get

      - name: PREPARATION before testing
        run: |
          echo "{" > secrets.json
          echo "Authorization=${{ secrets.BANGUMI_AUTHORIZATION }}" >> secrets.json
          echo "X-RapidAPI-Key=${{ secrets.RAPID_API_KEY }}" >> secrets.json
          echo "X-RapidAPI-Host=${{ secrets.RAPID_API_HOST }}" >> secrets.json
          echo "}" >> secrets.json

      - name: TEST the app
        run: flutter test

      # - name: START android release apk build
      #   run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info build/app/outputs/symbols --suppress-analytics

      - name: START android release app bundle build
        run: flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64 --obfuscate --split-debug-info build/app/outputs/bundlesymbols --suppress-analytics
      
      - name: UPLOAD android release app bundle
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab

  deploy:
    name: DEPLOY Android Build
    needs: android_build
    runs-on: ubuntu-latest
    steps:
  #     - uses: actions/checkout@v1

  #     - name: GET Android Build from artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: android-release
      
  #     - name: RELEASE Build to internal track
  #       uses: r0adkll/upload-google-play@v1
  #       with:
  #         serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
  #         packageName: com.kerojohn.alt_bangumi
  #         releaseFiles: app-release.aab
  #         track: before-production
  #         status: completed
      - uses: r0adkll/upload-google-play@9cf8fd30c9e616ec761db3b9abb2b0f15842ce58 # v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.kerojohn.alt_bangumi
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: before-production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib
  